### ISSUE TITLE
bug: mapping EntityWithTypedId<>

### ISSUE THREAD

**Issue by oishiimendesu** [codai/Sharp-Lite#10]
my Model inherit from EntityWithTypedId<string> 
when I run mapping throw this message:
----> NHibernate.MappingException : Cannot extend unmapped class: SharpLite.Domain.EntityWithTypedId`1

**Comment by rpmcnally** [comment]
Could you post a little more to show how you set everything up?  Do your models inherit directly from EntityWithTypeId or do you have a base Entity class?  Regardless, you will probably also have to modify NHibernateProvider.Conventions so that IsEntity() and IsRootEntity() work with your setup.

**Comment by oishiimendesu** [comment]
Model:
   public interface IPresupuesto
    {
        decimal Presupuestado { get; set; }
        decimal Comprometido { get; set; }
        decimal Consumido { get; set; }
        decimal Disponible { get; set; }
        string Id { get; }
    }
    [DebuggerDisplay("{Id}")]
    public class Presupuesto:EntityWithTypedId<string>, IPresupuesto
    {
        public virtual decimal Presupuestado { get; set; }
        public virtual decimal Comprometido { get; set; }
        public virtual decimal Consumido { get; set; }
        public virtual decimal Disponible { get; set; }
    }

---

NHibernateProvider.overrides:
 public class PresupuestoOverride:IOverride
    {
       public void Override(ModelMapper mapper)
        {
           mapper.Class<Presupuesto>(map=>
                                         {
                                             map.Table("PRESUPUESTO");
                                             map.Id(x=>x.Id,action=>
                                                                {
                                                                    action.Column("CUENTA");
                                                                    action.Generator(Generators.Assigned);
                                                                    action.Length(22);
                                                                });
                                         });
        }

##     }

NHibernateProvider:
 public static bool IsEntity(Type type)
        {
            var valid = (typeof(Entity).IsAssignableFrom(type) && typeof(Entity) != type
               || typeof(EntityWithTypedId<string>).IsAssignableFrom(type) && typeof(EntityWithTypedId<string>) != type) && !type.IsInterface;
            return valid;
        }

**Comment by hgirish** [comment]
Following changes to WithConventions method have worked for me along with above mentioned IsEntity method.

//     mapper.IsRootEntity((type, declared) => baseEntityType.Equals(type.BaseType));
       Type baseEntityTypeWithId = typeof(EntityWithTypedId<Guid>)
            mapper.IsRootEntity((type, declared)
                => (baseEntityType.Equals(type.BaseType) || baseEntityTypeWithId.Equals(type.BaseType)));

**Comment by hgirish** [comment]
Angled brackets were removed from previous comment.  It should be typeof(EntityWithTypedId&lt;&gt;)
