### ISSUE TITLE
bug in HasUniqueDomainSignatureAttribute.cs

### ISSUE THREAD

**Issue by qinking126** [codai/Sharp-Lite#2]
HasUniqueDomainSignatureAttribute kept returning the wrong error message on one of my new application using sharp lite.

I uploaded my codes on github, https://github.com/feelexit/DevelopmentStack

I detailed out the problem on this post.  http://groups.google.com/group/sharp-lite/browse_thread/thread/27cb231e48cd2b49

Seif helped to fix it. To fix it,  He changed HasUniqueDomainSignatureAttribute.cs 

https://github.com/seif/DevelopmentStack/commit/f1188c4c75453e331d58ed9a5eebfbdefcc14699

please verify if this is  indeed a bug.

**Comment by codai** [comment]
feelexit, thank you for reporting this as well...it is very much appreciated (even if not promptly replied to).  I have made the change on my machine and will do a push over the weekend.
