### ISSUE TITLE
NHibernateConfigurationFileCache for Sharp Lite

### ISSUE THREAD

**Issue by nazjunaid** [codai/Sharp-Lite#4]
In Sharp Arch 1.9.6 we depended on the NHibernateConfigurationFileCache feature which dramatically reduced our application start up time. 

I noticed this feature missing from Sharp Lite and was wondering if there was a reason for it? Is this something that can be added and used alongside the new 3.2 method of Nhibernate configuration.

**Comment by codai** [comment]
This has been fixed.
